version: '3.8'

services:
  # Base de données MySQL pour les données structurées
  mysql:
    image: mysql:8.0
    container_name: ecoride_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password_secure
      MYSQL_DATABASE: ecoride_db
      MYSQL_USER: ecoride_user
      MYSQL_PASSWORD: ecoride_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/structure.sql:/docker-entrypoint-initdb.d/01_structure.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/02_data.sql
    ports:
      - "3306:3306"
    networks:
      - ecoride_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Base de données MongoDB pour les préférences et logs
  mongodb:
    image: mongo:6.0
    container_name: ecoride_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: mongo_password_secure
      MONGO_INITDB_DATABASE: ecoride_nosql
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    networks:
      - ecoride_network

  # Application PHP avec Apache
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecoride_webapp
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_started
    environment:
      # Configuration base de données MySQL
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ecoride_db
      DB_USER: ecoride_user
      DB_PASSWORD: ecoride_password
      
      # Configuration MongoDB
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USER: mongo_admin
      MONGO_PASSWORD: mongo_password_secure
      MONGO_DB: ecoride_nosql
      
      # Configuration application
      APP_ENV: development
      APP_DEBUG: true
      APP_URL: http://localhost:8080
      
      # Configuration des crédits
      INITIAL_CREDITS: 20
      PLATFORM_FEE_CREDITS: 2
      
      # Configuration mail (si nécessaire)
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: your_email@gmail.com
      MAIL_PASSWORD: your_app_password
      
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/html/src
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
    ports:
      - "8080:80"
    networks:
      - ecoride_network

  # PHPMyAdmin pour la gestion MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: ecoride_phpmyadmin
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ecoride_user
      PMA_PASSWORD: ecoride_password
      MYSQL_ROOT_PASSWORD: root_password_secure
    ports:
      - "8081:80"
    networks:
      - ecoride_network

  # Mongo Express pour la gestion MongoDB
  mongo-express:
    image: mongo-express:1.0
    container_name: ecoride_mongo_express
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo_password_secure
      ME_CONFIG_MONGODB_URL: mongodb://mongo_admin:mongo_password_secure@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - "8082:8081"
    networks:
      - ecoride_network

  # Redis pour la gestion des sessions et cache
  redis:
    image: redis:7-alpine
    container_name: ecoride_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass redis_password_secure
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - ecoride_network

  # Service de sauvegarde automatique
  backup:
    image: alpine:latest
    container_name: ecoride_backup
    restart: "no"
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_started
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ecoride_user
      MYSQL_PASSWORD: ecoride_password
      MYSQL_DATABASE: ecoride_db
      MONGO_HOST: mongodb
      MONGO_USER: mongo_admin
      MONGO_PASSWORD: mongo_password_secure
    volumes:
      - ./backups:/backups
      - ./scripts/backup.sh:/backup.sh
    networks:
      - ecoride_network
    command: >
      sh -c "
      apk add --no-cache mysql-client mongodb-tools &&
      chmod +x /backup.sh &&
      /backup.sh
      "

# Définition des volumes persistants
volumes:
  mysql_data:
    driver: local
  mongodb_data:
    driver: local
  redis_data:
    driver: local

# Définition du réseau
networks:
  ecoride_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16