version: '3.8'

services:
  # Base de données MySQL pour les données structurées
  mysql:
    image: mysql:8.0
    container_name: ecoride_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/structure.sql:/docker-entrypoint-initdb.d/01_structure.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/02_data.sql
    ports:
      - "3306:3306"
    networks:
      - ecoride_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Application PHP avec Apache
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecoride_webapp
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # Configuration base de données MySQL
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      
      # Configuration application
      APP_ENV: development
      APP_DEBUG: true
      APP_URL: http://localhost:8080
      
      # Configuration des crédits
      INITIAL_CREDITS: ${INITIAL_CREDITS}
      PLATFORM_FEE_CREDITS: ${PLATFORM_FEE_CREDITS}
      
      # Configuration mail (si nécessaire)
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    networks:
      - ecoride_network

  # PHPMyAdmin pour la gestion MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: ecoride_phpmyadmin
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - ecoride_network

  # Redis pour la gestion des sessions et cache
  redis:
    image: redis:7-alpine
    container_name: ecoride_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - ecoride_network

  # Service de sauvegarde automatique
  backup:
    image: alpine:latest
    container_name: ecoride_backup
    restart: "no"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./backups:/backups
      - ./scripts/backup.sh:/backup.sh
    networks:
      - ecoride_network
    command: >
      sh -c "
      apk add --no-cache mysql-client &&
      chmod +x /backup.sh &&
      /backup.sh
      "

# Définition des volumes persistants
volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

# Définition du réseau
networks:
  ecoride_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16